# Generated by Django 4.2 on 2023-07-21 05:55

import account.models
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_useraccount_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=account.models.CustomDateTimeField(default=datetime.datetime(2023, 7, 21, 5, 55, 52, tzinfo=datetime.timezone.utc)),
        ),
    ]
